sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with deockerfile"
  - docker build -t lyg0516/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true lyg0516/docker-react-app npm run test -- --coverage

deploy:
  provider: elsticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  environment: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-439687180680"
  bucket-path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY