sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with deockerfile"
  - docker build -t lyg0516/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true lyg0516/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"